"""empty message

Revision ID: af2bb3f674e4
Revises: b45373dad4eb
Create Date: 2023-04-28 12:46:35.180194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2bb3f674e4'
down_revision = 'b45373dad4eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_menu',
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['t_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_role_menu')
    # ### end Alembic commands ###
