"""empty message

Revision ID: b45373dad4eb
Revises: 2018213c52e6
Create Date: 2023-04-27 16:49:11.129193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45373dad4eb'
down_revision = '2018213c52e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_user', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    op.drop_column('t_user', 'rid')
    # ### end Alembic commands ###
